In [3]:
import numpy as np

In [11]:
# Membuat array numpy 1D
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Membuat array numpy 2D
arr_2d = np.array([[1, 2, 3,], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [17]:
#menjumlahkan/mengalikan array
arr = np.array([1, 2, 3,])
print(arr + 5)
print(arr * 2)

[6 7 8]
[2 4 6]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr)) # menjumlahkan elemen 
print(np.mean(arr)) # rata - rata elemen 
print(np.max(arr)) # nilai maksimum
print(np.min(arr)) # nilai minimum 

15
3.0
5
1


In [27]:
# cara lain membuat array
arr = np.arange(0, 10, 2) #membuat array dari 0 hingga 9 dengan step 2
print(arr)

[0 2 4 6 8]


In [29]:
arr_2d = np.array([[1, 2, 3,], [4, 5, 6]])
print(np.sum(arr_2d, axis=0)) #Menjumlahkan setiap kolom 
print(np.sum(arr_2d, axis=1)) #Menjumlahkan setiap baris

[5 7 9]
[ 6 15]


In [33]:
#Mengubah array satu menjadi dua dimensi dengan reshape
arr = np.arange(1,13)
print(arr)
arr_reshaped = arr.reshape(3,4) #Mengubah bentuk array menjadi 3x4
print(arr_reshaped) 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
#Menyeleksi array
arr = np.array([10,20,30,40,50])
mask = arr > 30
print(arr[mask]) #Menampilkan elemen yang leboh besar dari 30

[40 50]


In [43]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined = np.concatenate ((arr1, arr2)) # Menggabungkan array
print (combined)

split = np.split(combined, 2) #Membagi array menjadi dua bagian
print(split)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


In [45]:
rand_arr= np.random.rand(3, 3) # Membuat array 3x3 dengan nilai random antara 0 dan 1 
print(rand_arr)

randint_arr = np.random.randint(1, 10, size=(2, 3)) # Membuat array 2x3 dengan angka integer random 
print(randint_arr)

[[0.79928208 0.2421206  0.72798739]
 [0.37533121 0.49832307 0.87725316]
 [0.94203898 0.15623922 0.40629442]]
[[7 2 3]
 [7 5 7]]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
print(arr + scalar) # Broadcasting menambah semua elemen dengan scalar

[[11 12 13]
 [14 15 16]]


In [51]:
# Perkalian matriks
A = np.array([[1, 2], [3, 4]])
B= np.array([[5, 6], [7, 8]])
result = np.dot (A, B) # Perkalian matriks
print(result)

# Invers matriks
A_inv = np.linalg.inv(A)
print(A_inv)

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [53]:
matrix = np.array([[1, 2], [2, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [ 3. -1.]
Eigenvectors: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [57]:
arr = np.array ([4, 2, 7, 1])
sorted_arr= np.sort(arr) # Mengurutkan array 
print(sorted_arr)
indices = np.argsort(arr) # Mendapatkan indeks array yang diurutkan 
print(indices)

[1 2 4 7]
[3 1 0 2]


In [59]:
arr = np.array([10, 20, 30, 40])
result = np.where(arr> 20, arr, 1) # Ganti elemen yang Lebih kecil dari 20 dengan -1 
print(result)

[ 1  1 30 40]


In [65]:
arr = np.array([1, 2, np.nan, 4, 5]) 
print(np.isnan(arr)) # Memeriksa elemen NaN

#Mengisi nilai Nan dengan rata-rata elemen Lainnya 
arr[np.isnan(arr)] = np.nanmean(arr) 
print(arr)

[False False  True False False]
[1. 2. 3. 4. 5.]


In [67]:
arr = np.array ([1, 2, 3, 4, 5])
result = np.sin(arr) # Menerapkan fungsi sinus pada setiap elemen array 
print(result)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [77]:
import time

# Menggunakan Loop biasa
start = time.time()
result = [i**2 for i in range(100000)]
end = time.time()
print("Waktu dengan loop biasa:", end - start)

# Menggunakan Numpy
start = time.time()
arr = np.arange(100000)
result = arr**2
end = time.time()
print("Waktu dengan Numpy:", end - start)

Waktu dengan loop biasa: 0.009441852569580078
Waktu dengan Numpy: 0.0019991397857666016


In [91]:
# Latihan : 
# Soal: Buatlah array Numpy berisi angka dari 1 sampai 10.
array_1_to_10 = np.arange(1, 11)
print(array_1_to_10)

print("\n" + "-"*30 + "\n")

# Soal 2 : Buat array dari 1 hingga 5, lalu kalikan setiap elemennya dengan 3.
array_1_to_5 = np.arange(1, 6)
array_multiplied = array_1_to_5 * 3  # Mengalikan setiap elemen dengan 3
print(array_multiplied)

print("\n" + "-"*30 + "\n")

# Soal 3 : Buatlah matriks identitas berukuran 3x3.
identity_matrix = np.eye(3)
print(identity_matrix)

print("\n" + "-"*30 + "\n")

#Soal 4 : Buat array acak berukuran 5x5, lalu cari nilai maksimum dalam array tersebut.
random_array = np.random.rand(5, 5)
max_value = np.max(random_array)   # Mencari nilai maksimum dalam array
print(random_array)
print("Nilai maksimum:", max_value)

print("\n" + "-"*30 + "\n")

#Soal 5 : Buat array 1D dengan 9 elemen, lalu ubah menjadi array 2D dengan ukuran 3x3.
array_1d = np.arange(1, 10)
array_2d = array_1d.reshape(3, 3)  # Mengubah menjadi array 2D ukuran 3x3
print(array_2d)

print("\n" + "-"*30 + "\n")

#Soal 6 : Berikan dua matriks 3x3, hitung hasil perkalian dot product kedua matriks tersebut.
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
dot_product = np.dot(matrix_a, matrix_b) # Menghitung dot product dari kedua matriks
print(dot_product)

print("\n" + "-"*30 + "\n")

#Soal 7 : Buat array 1D dari 1 hingga 10, kemudian ambil elemen pada indeks 3 sampai 7.
array_1d = np.arange(1, 11)
sliced_array = array_1d[3:8]  # Index 3 hingga 7 (Python slicing tidak termasuk indeks terakhir)
print(sliced_array)

print("\n" + "-"*30 + "\n")

#Soal 8 : Gabungkan dua array a = [1, 2, 3] dan b = [4, 5, 6] menjadi satu array.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concatenated_array = np.concatenate((a, b)) # Menggabungkan kedua array
print(concatenated_array)

print("\n" + "-"*30 + "\n")

#Soal 9 : Buat array berisi angka 1 hingga 4, kemudian tambahkan 10 ke setiap elemen array tersebut dengan menggunakan broadcasting.
array_broadcast = np.array([1, 2, 3, 4])
array_broadcast = array_broadcast + 10 # Menambahkan 10 ke setiap elemen menggunakan broadcasting
print(array_broadcast)

print("\n" + "-"*30 + "\n")

#Soal 10 : Buat array acak berisi 10 elemen, lalu urutkan array tersebut.
random_array = np.random.rand(10)
sorted_array = np.sort(random_array) # Mengurutkan array
print("Array acak:", random_array)
print("Array setelah diurutkan:", sorted_array)

[ 1  2  3  4  5  6  7  8  9 10]

------------------------------

[ 3  6  9 12 15]

------------------------------

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

------------------------------

[[0.59329526 0.72368762 0.04103326 0.84629991 0.94085228]
 [0.47167252 0.90332805 0.56122618 0.34573675 0.16324592]
 [0.09302034 0.94608073 0.54106191 0.46603515 0.20825885]
 [0.75128046 0.87206091 0.59807572 0.80621347 0.01975992]
 [0.55977471 0.97874407 0.36326518 0.20221308 0.87325328]]
Nilai maksimum: 0.9787440742760533

------------------------------

[[1 2 3]
 [4 5 6]
 [7 8 9]]

------------------------------

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

------------------------------

[4 5 6 7 8]

------------------------------

[1 2 3 4 5 6]

------------------------------

[11 12 13 14]

------------------------------

Array acak: [0.6911308  0.39162551 0.48969839 0.36065095 0.89892598 0.26874169
 0.03963329 0.27447588 0.88870595 0.33004876]
Array setelah diurutkan: [0.03963329 0.26874169 0.27